version: "3"
services:
  app:
    build:
      context: react-native
      args:
        NODE_ENV: development
    tty: true
    stdin_open: true
    ports:
      - 8081:8081
      - 19001:19001
      - 19002:19002
      - 19006:19006
    volumes:
      - ./react-native:/opt/react_native_app
      - ./directus:/opt/directus
      - /opt/directus/extensions/directus-extension-endpoint-recipe-add-image/node_modules # ignore node modules
      - /opt/directus/extensions/directus-extension-hook-recipe-delete-image/node_modules # ignore node modules
      - /opt/directus/extensions/directus-extension-hook-user-delete-files/node_modules # ignore node modules
      - /opt/directus/scripts/node_modules # ignore node modules
      #- ./directus:/opt/react_native_app/directus
      #- ./app:/opt/react_native_app/app
      #- ./lib:/opt/react_native_app/lib
      #- ./package.json:/opt/react_native_app/package.json
      - ./react-native/node_modules:/opt/react_native_app/node_modules
    environment:
      DIRECTUS_LOCAL_URL: ${DIRECTUS_LOCAL_URL:-http://directus:8055}
      DIRECTUS_STAGING_URL: ${DIRECTUS_STAGING_URL}
      DIRECTUS_LOCAL_ACCESS_TOKEN: ${DIRECTUS_LOCAL_ACCESS_TOKEN}
      DIRECTUS_STAGING_ACCESS_TOKEN: ${DIRECTUS_STAGING_ACCESS_TOKEN}
      EXPO_PUBLIC_DIRECTUS_URL: ${DIRECTUS_LOCAL_URL:-http://localhost:8055}
      EXPO_PUBLIC_DIRECTUS_LOCAL_USER_CREATE_PUBLIC_TOKEN: ${DIRECTUS_LOCAL_USER_CREATE_PUBLIC_TOKEN}

  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.10.7
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: ${DIRECTUS_KEY} # is only used as an identifier in multi-container setups
      SECRET: ${DIRECTUS_SECRET} # is used by the Directus API to sign JWTs for the Directus frontend
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_USER}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CORS_METHODS: GET,POST,PATCH,DELETE,OPTIONS
      EXTENSIONS_AUTO_RELOAD: "true"
      CACHE_AUTO_PURGE: "true"
      EXTENSION_MAX_PAYLOAD_SIZE: "2"
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
volumes:
  postgres_data:
  node_modules: